# Generated by Django 2.1 on 2018-08-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Luhuo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='下单日期')),
                ('platform', models.CharField(choices=[('tb', '淘宝'), ('tm', '天猫'), ('mn', '猫宁'), ('sn', '苏宁'), ('jd', '京东')], max_length=2)),
                ('order_num', models.CharField(max_length=50, verbose_name='订单号')),
                ('product', models.CharField(max_length=100, verbose_name='产品名称')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('price', models.FloatField(verbose_name='价格')),
                ('money', models.FloatField(default=0.0, verbose_name='金额')),
                ('gather', models.FloatField(default=0.0, verbose_name='收款')),
            ],
            options={
                'verbose_name': '撸货订单',
                'verbose_name_plural': '撸货订单',
            },
        ),
    ]
